# Generated by Django 5.0.6 on 2024-07-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_suscriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscriber',
            new_name='Subscriber',
        ),
    ]
