# Generated by Django 5.0.6 on 2024-07-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='Noamelink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
